name: DCCore
author: Jacksonnn
version: BETA 1.0
main: com.Jacksonnn.DCCore.DCCore
loadbefore: [Essentials, Playtimes, DiscordSRVMy ]
api-version: 1.13
commands:
  dccore:
    aliases: [dc,dcc,dcore]
    usage: /<command>
  broadcast:
    aliases: [bc, bcast]
    usage: /<command>
  bannedwords:
    aliases: [bw, bwords, bannedw]
    usage: /<command>
  bendingtournament:
    aliases: [bt, tournament, tourney, bendingt, btournament, btourny]
    usage: /<command>
  rankup:
    aliases: [ru, rank, rup]
    usage: /<command>
  playtime:
    usage: /<command>
  ranks:
    usage: /<command>
  diamondluck:
    aliases: [diamondl, dluck, dl]
    usage: /<command>
  randomtp:
    aliases: [randtp, randomteleport, rtp, randteleport]
    usage: /<command>
  dcevents:
    aliases: [events, dce, darkcrestevents, darkcreste]
    usage: /<command>
  b:
    aliases: [pk, projectkorra, bend, bending, atla, alok, tla, lok]
    usage: /<command>
  donate:
    usage: /<command>
  vote:
    usage: /<command>
  forums:
    aliases: [forum, board]
    usage: /<command>
  website:
    aliases: [site, web, www]
    usage: /<command>
  bendinghelp:
    aliases: [bhelp, bendingh, bh]
    usage: /<command>
  avatar:
    usage: /<command>
  lightspirit:
    usage: /<command>
  darkspirit:
    usage: /<command>
  bendingfix:
    aliases: [fixbending, bfix, bendingf]
    usage: /<command>
  headofstaff:
    aliases: [hos, headostaff, bigstaff, daddystaff]
    usage: /<command>
  managers:
    aliases: [ms, admins, managerchat, mchat]
    usage: /<command>
  developer:
    aliases: [devs, developers, dev]
    usage: /<command>
  eventhosts:
    aliases: [eh, eventhost, ehosts]
    usage: /<command>
  moderators:
    aliases: [mods, jmods, serverstaff, jrmoderators, jrmods, babystaff]
    usage: /<command>
  staffchat:
    aliases: [staff, combinedstaff, cstaff]
    usage: /<command>
  artists:
    aliases: [builders, artistsonly, artistic, artistchat]
    usage: /<command>
  staffcount:
    usage: /<command>
  notes:
    aliases: [note, playernotes]
    usage: /<command>
  warnings:
    aliases: [warning, warn, warns]
    usage: /<command>
  reports:
    aliases: [report]
    usage: /<command>
  announcer:
    aliases: [announcements, dca, dcannouncements, acannounce, announce, dcannouncer]
    usage: /<command>
  staffspawn:
    aliases: [ss, specialspawn]
    usage: /<command>
  banish:
    aliases: [bannish, woosh, piss]
    usage: /<command>
  playerinfo:
    aliases: [pi, pinfo, playeri]
    usage: /<command>
permissions:
  DCCore.player:
    default: op
    children:
      DCCore.spawner.place: true
      DCCore.spawner.break: true
      DCCore.QuickDeposit.use: true
      DCCore.RandomTP.self: true
  DCCore.staff:
    default: op
    children:
      DCCore.GMSpectator: true
      DCCore.broadcast: true
      DCCore.chat: true
      DCCore.staff.announcements: true
      DCCore.staff.Vanish: true
      DCCore.RandomTP.others: true
      DCCore.NotesStaff: true
      DCCore.ReportStaff: true
      DCCore.WarningStaff: true
      DCCore.PlayerInfo: true
  DCCore.chat:
    default: op
    children:
      DCCore.chat.toggle: true
      DCCore.chat.staff: true
      DCCore.AntiCurse.bypass: true
      DCCore.bannedwords: true